### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by codevonnie** [UnderDev/TVI_Cinema#2]
Movies 
- Description
- Cast/Director
- Film Rating
- Movie Poster Image
- Trailer URL
- Length
- Screen (PK)

Times
- Time
- Screen (FK)
- 2D/3D

Prices
- Ticket Type
- Price
- 2D/3D (Boolean)

**Comment by codevonnie** [comment]
Coming Soon 
- Description
- Cast/Director
- Film Rating
- Movie Poster Image
- Trailer URL
- Length

**Comment by Rabhimself** [comment]
Here's a database setup script to get us started.

https://gist.github.com/Rabhimself/c8a0a00e28bd8837a981

**Comment by Rabhimself** [comment]
These should build the databases for SQL Express.

Make sure you put the image files in the correct spot. You can find the path and file names in the dbo.Movies.data.sql file. Each insert statement has it, similar to how blobs are uploaded in MySQL.

https://gist.github.com/Rabhimself/93e94f84961b9c0b9e74

**Comment by Rabhimself** [comment]
Consider adding another table for each "fillum's" cast.
